name: Release

on:
  push:
    tags: ['v*']

permissions: {}

env:
  GORELEASER_VERSION: v2.18.0

jobs:
  release:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
      - name: Validate release tag
        shell: bash
        run: |
          if [[ ! "$GITHUB_REF_NAME" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-(alpha|beta|rc)\.(0|[1-9][0-9]*))?$ ]]; then
            echo "Unsupported release tag: $GITHUB_REF_NAME" >&2
            exit 1
          fi
          git fetch --no-tags origin master:refs/remotes/origin/master
          if ! git merge-base --is-ancestor "$GITHUB_SHA" origin/master; then
            echo "Release tag must point to a commit on origin/master" >&2
            exit 1
          fi
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
      - uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
